currency_symbols = {
    'USD': '$',
    'EUR': '€',
    'UAH': '₴',
    'GBP': '£',
    'JPY': '¥',
    'AUD': 'A$',
    'CAD': 'C$',
    'CHF': 'CHF',
    'INR': '₹',
    'CNY': '¥',
    'RUB': '₽',
    'BRL': 'R$',
    'MXN': '$',
    'ZAR': 'R',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'PLN': 'zł',
    'TRY': '₺',
    'HKD': 'HK$',
    'SGD': 'S$',
    'MYR': 'RM',
    'KRW': '₩',
    'TWD': 'NT$',
    'SAR': 'ر.س',
    'AED': 'د.إ',
}